server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/complitech?currentSchema=complitech
    username: complitech
    password: complitech
    hikari:
      connection-timeout: 3000
      idle-timeout: 60000
      maximum-pool-size: 40
      max-lifetime: 10000
      minimum-idle: 10
      schema: complitech
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+3
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
        hbm2ddl:
          auto: validate
    open-in-view: off
  liquibase:
    change-log: classpath:migration/changelog-master.xml
    enabled: true
    user: complitech
    password: complitech
    url: jdbc:postgresql://localhost:5432/complitech
    driver-class-name: org.postgresql.Driver
    default-schema: complitech

jwt:
  secret: 12asedgfasdlur2345183ryhbqfqew543qfsgfasdga34
  accessTokenExpiration: 36000000
  refreshTokenExpiration: 604800000

shutdown:
  datetime: "2024-12-01T00:00:00"

pagination:
  page: 1
  limit: 20
  sort: ASC
