create table complitech.auth_token
(
    id                   int4 generated by default as identity (start with 1 increment by 1) not null,
    access_token         varchar(2048)                                                       not null unique,
    refresh_token        varchar(2048)                                                       not null unique,
    is_revoked           boolean                                                             not null default false,
    is_expired           boolean                                                             not null default false,
    user_id              int4                                                                not null,
    refresh_token_expiry timestamp with time zone                                            not null,
    created_by           varchar(128),
    created_at           timestamp with time zone,
    modified_by          varchar(128),
    updated_at           timestamp with time zone,

    constraint pk__auth_token__id primary key (id),
    constraint fk__auth_token__user__id foreign key (user_id)
        references complitech.user (id) on delete cascade
);
