create table complitech.gender_type
(
    id   int2 generated by default as identity (start with 1 increment by 1) not null,
    name varchar(128)                                                        not null,

    constraint pk__gender_type__id primary key (id),
    constraint uq__gender_type__name unique (name)
);

insert into complitech.gender_type (id, name)
values (1, 'Мужской'),
       (2, 'Женский'),
       (3, 'Не задано');