create table complitech.user
(
    id          int4 generated by default as identity (start with 1 increment by 1) not null,
    login       varchar(50)                                                         not null,
    password    varchar(1024)                                                       not null,
    full_name   varchar(256)                                                        not null,
    gender_id   int2                                                                not null,
    user_role   varchar(50),
    created_by  varchar(128)                                                        not null,
    created_at  timestamp with time zone                                            not null,
    modified_by varchar(128),
    updated_at  timestamp with time zone,

    constraint pk__user__id primary key (id),
    constraint fk__user__gender_type__id foreign key (gender_id)
        references complitech.gender_type (id)
);

